/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapptest01.form;

import javaapptest01.form.constant.MyUIConstants;

/**
 *
 * @author Dules
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiAddTeacher = new javax.swing.JMenuItem();
        jmiViewAllTeacherForm = new javax.swing.JMenuItem();
        jmiViewEditAllTeacherForm = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Opcije");

        jmiAddTeacher.setText("Dodaj nastavnika");
        jmiAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAddTeacherActionPerformed(evt);
            }
        });
        jMenu1.add(jmiAddTeacher);

        jmiViewAllTeacherForm.setText("Prikaz nastavnika");
        jmiViewAllTeacherForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewAllTeacherFormActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewAllTeacherForm);

        jmiViewEditAllTeacherForm.setText("Prikaz i izmena nastavnika u tabeli");
        jmiViewEditAllTeacherForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiViewEditAllTeacherFormActionPerformed(evt);
            }
        });
        jMenu1.add(jmiViewEditAllTeacherForm);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAddTeacherActionPerformed
        new TeacherFom(this, true, MyUIConstants.ADD_TEACHER).setVisible(true);
    }//GEN-LAST:event_jmiAddTeacherActionPerformed

    private void jmiViewAllTeacherFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewAllTeacherFormActionPerformed
        new TeacherViiewAllForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiViewAllTeacherFormActionPerformed

    private void jmiViewEditAllTeacherFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiViewEditAllTeacherFormActionPerformed
        new TeacherViiewEditAllForm(this, true).setVisible(true);
    }//GEN-LAST:event_jmiViewEditAllTeacherFormActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiAddTeacher;
    private javax.swing.JMenuItem jmiViewAllTeacherForm;
    private javax.swing.JMenuItem jmiViewEditAllTeacherForm;
    // End of variables declaration//GEN-END:variables
}
