/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaapptest01.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapptest01.controller.Controller;
import javaapptest01.domain.AcademicTitle;
import javaapptest01.domain.Teacher;
import javaapptest01.form.components.table.model.TeacherTableModel;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author Dules
 */
public class TeacherViiewEditAllForm extends javax.swing.JDialog {

    /**
     * Creates new form TeacherViiewAllForm
     */
    public TeacherViiewEditAllForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        populateTableTeachers();
        prepareTableTeachers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeachers = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTeachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTeachers);

        btnAdd.setText("Dodaj novi red");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Obrisi red");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnUpdate.setText("Sinhronizuj");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(733, 733, 733)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAdd)
                        .addGap(32, 32, 32)
                        .addComponent(btnRemove)
                        .addGap(32, 32, 32)
                        .addComponent(btnUpdate)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        //vidi koji je red izabran
        int selectedRow = tblTeachers.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Izaberite red u tabeli!");
        } else {
            TeacherTableModel ttm = (TeacherTableModel) tblTeachers.getModel();
            ttm.remove(selectedRow);
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        //sve iz tabele tblTeacher, sacuvaj u tabeli u bazi nastavnik

        //uzmi sve nastavnike iz tabele
        TeacherTableModel tm = (TeacherTableModel) tblTeachers.getModel();
        List<Teacher> teachers = tm.getTeachers();
        try {
            //ove nastavnike sacuvaj ili dodaj u tabelu
            new Controller().update(teachers, tm.getRemovedTeachers());
            JOptionPane.showMessageDialog(this, "Uspesno azuriranje!");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //dodaj novi red u tabelu
        TableModel tm = tblTeachers.getModel();
        TeacherTableModel ttm = (TeacherTableModel) tm;
        ttm.addEmptyRow();
    }//GEN-LAST:event_btnAddActionPerformed
    private void populateTableTeachers() {
        List<Teacher> teachers;
        try {
            teachers = new Controller().getAllTeachers();
            TableModel tmt = new TeacherTableModel(teachers);
            tblTeachers.setModel(tmt);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTeachers;
    // End of variables declaration//GEN-END:variables

    private void prepareTableTeachers() {
        try {
            //promeni default editor komponentu za kolonu u zvanje

            //kreiraj kombobox i popuni sa zvanjima
            List<AcademicTitle> titles = new Controller().getAllAcademicTitle();
            ComboBoxModel modelAcademicTitle = new DefaultComboBoxModel(titles.toArray());
            JComboBox comboTitles = new JComboBox(modelAcademicTitle);

            //postavi combobox da bude editor za kolonu zvanje
            TableColumn tc = tblTeachers.getColumnModel().getColumn(2);
            tc.setCellEditor(new DefaultCellEditor(comboTitles));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

}
