/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapptest01.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapptest01.controller.Controller;
import javaapptest01.domain.AcademicTitle;
import javaapptest01.domain.Teacher;
import javaapptest01.form.constant.MyUIConstants;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Dules
 */
public class TeacherFom extends javax.swing.JDialog {

    private int mode;
    private Teacher teacher;

    /**
     * Creates new form TeacherFom
     */
    public TeacherFom(JFrame parent, boolean modal, int mode) {
        super(parent, modal);
        initComponents();
        this.mode = mode;
        populateComboAcademicTitles();
        prepareForm();
    }

    public TeacherFom(JFrame parent, boolean modal, int mode, Teacher teacher) {
        super(parent, modal);
        initComponents();
        this.mode = mode;
        this.teacher = teacher;
        populateComboAcademicTitles();
        prepareForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        comboAcademicTitle = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnEnableChanges = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();

        jLabel1.setText("Ime:");

        jLabel2.setText("Prezime:");

        jLabel3.setText("Zvanje:");

        comboAcademicTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setText("Obrisi");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnEnableChanges.setText("Omoguci izmenu");
        btnEnableChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnableChangesActionPerformed(evt);
            }
        });

        jLabel4.setText("ID:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEnableChanges)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboAcademicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtFirstname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                                .addComponent(txtLastname, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(comboAcademicTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSave)
                    .addComponent(btnDelete)
                    .addComponent(btnEnableChanges))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEnableChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnableChangesActionPerformed
        this.mode = MyUIConstants.EDIT_TEACHER;
        prepareForm();
    }//GEN-LAST:event_btnEnableChangesActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String firstname = txtFirstname.getText().trim();
        String lastname = txtLastname.getText().trim();
        AcademicTitle academicTitle
                = (AcademicTitle) comboAcademicTitle.getSelectedItem();

        if (this.mode == MyUIConstants.ADD_TEACHER) {
            //izvrsi validaciju
            if (!firstname.isEmpty() && !lastname.isEmpty()) {
                Teacher newTeacher = new Teacher();
                newTeacher.setFirstname(firstname);
                newTeacher.setLastname(lastname);
                newTeacher.setAcademicTitle(academicTitle);

                int option = JOptionPane.showConfirmDialog(this, "Da li zelite da sacuvate nastavnika?", "Cuvanje entiteta", JOptionPane.YES_NO_OPTION);
                if (option == JOptionPane.YES_OPTION) {
                    try {
                        new Controller().saveTeacher(newTeacher);
                        JOptionPane.showMessageDialog(this, "Nastavnik sacuvan!");
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, ex.getMessage());
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Odustajem");
                    dispose();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Nisu uneti svi podaci!");
            }
        }else if (this.mode== MyUIConstants.EDIT_TEACHER){
            JOptionPane.showMessageDialog(this, "Izvrsi update!");
        }


    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEnableChanges;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> comboAcademicTitle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLastname;
    // End of variables declaration//GEN-END:variables

    private void populateComboAcademicTitles() {
        comboAcademicTitle.removeAllItems();
        try {
            //popini combo
            List<AcademicTitle> titles = new Controller().getAllAcademicTitle();
            comboAcademicTitle.setModel(new DefaultComboBoxModel(titles.toArray()));
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void prepareForm() {
        switch (mode) {
            case MyUIConstants.ADD_TEACHER: {
                txtId.setEnabled(false);
                btnDelete.setEnabled(false);
                btnEnableChanges.setEnabled(false);
                btnSave.setEnabled(true);
                comboAcademicTitle.setEditable(true);
                break;
            }
            case MyUIConstants.EDIT_TEACHER: {
                txtId.setEnabled(false);
                txtFirstname.setEnabled(true);
                txtLastname.setEnabled(true);
                comboAcademicTitle.setEditable(true);

                btnDelete.setEnabled(false);
                btnEnableChanges.setEnabled(false);
                btnSave.setEnabled(true);
                break;
            }
            case MyUIConstants.VIEW_TEACHER: {
                txtId.setEnabled(false);
                txtFirstname.setEnabled(false);
                txtLastname.setEnabled(false);
                comboAcademicTitle.setEditable(false);

                btnDelete.setEnabled(true);
                btnEnableChanges.setEnabled(true);
                btnSave.setEnabled(false);

                txtId.setText(teacher.getId() + "");
                txtFirstname.setText(teacher.getFirstname());
                txtLastname.setText(teacher.getLastname());
                comboAcademicTitle.setSelectedItem(teacher.getAcademicTitle());
                break;
            }
        }
    }
}
