/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package javaapptest01.form;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javaapptest01.controller.Controller;
import javaapptest01.domain.Teacher;
import javaapptest01.form.components.table.model.TeacherTableModel;
import javaapptest01.form.constant.MyUIConstants;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Dules
 */
public class TeacherViiewAllForm extends javax.swing.JDialog {

    /**
     * Creates new form TeacherViiewAllForm
     */
    public TeacherViiewAllForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        populateTableTeachers();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeachers = new javax.swing.JTable();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTeachers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTeachers);

        btnDetails.setText("Detalji");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDetails)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDetails)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        int row = tblTeachers.getSelectedRow();
        if (row == -1 ){
            JOptionPane.showMessageDialog(this, "Izaberite nastavnika!");
        }else{
            //uzmi nastvanika
            TeacherTableModel ttm = (TeacherTableModel) tblTeachers.getModel();
            Teacher teacher = ttm.getRow(row);
            
            new TeacherFom(null, true,MyUIConstants.VIEW_TEACHER, teacher).
                    setVisible(true);
        }
    }//GEN-LAST:event_btnDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTeachers;
    // End of variables declaration//GEN-END:variables

    private void populateTableTeachers() {
        List<Teacher> teachers;
        try {
            teachers = new Controller().getAllTeachers();
            TableModel tmt = new TeacherTableModel(teachers);
            tblTeachers.setModel(tmt);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}
